version: "2.2"

services:

  gleif:
    container_name: gleif
    image: node:9.4.0-alpine
    init: true
    env_file: .env
    user: node
    working_dir: /home/node/gleif
    expose:
      - "8080"
    ports:
     - "3081:8080"
    networks:
      network:
        aliases:
          - gleif
    volumes:
      - "./:/home/node/gleif"
    command: npx nodemon ./index.js

networks: 
  network: 
